apiVersion: v1
kind: Secret
metadata:
    name: ecommerce-database-secret
    namespace: ecommerce
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:R398QA==,iv:xvcVFdnaBom5bYcyPWxGAuHP4oeBeG1uH04CeSJ7oFA=,tag:83eKnVkcTfPJrr6GTpCbWg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rgD1RJRT0ZTIXIE=,iv:oEmRVR5c6cbyCD8XlDfFb+GycSy45gOUvOZ1n7Dg6Mk=,tag:eslEyXJxgDfQ1VVcN9ayGw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-06-11T06:51:49Z"
          enc: CiQAFqaNNHq3TQJ+p/SGMuq13ZLxhBhxuDCdgD9XJXlpeGdKwAUSSQA/cA2ijkzmekomPw8qKUxN9Fz4dNiGiYTnTVq8wIjmAs468thlgDuZFg5I/5PHwvprlG2ce/PFBmTUWIfjyqaVJoBRq1tqI3Y=
          resource_id: projects/project-e42a7d8e-d909-49f2-944/locations/asia-northeast1/keyRings/sops-secret/cryptoKeys/sops-key-secret
    lastmodified: "2026-06-11T06:51:49Z"
    mac: ENC[AES256_GCM,data:QquaSZL/hJyY0FFLKm6I72ICUcsjP1sR9AeD5js/u82ratpryYrW9Z7G6Lva5ohv0HlD65veV0Y80Ws3Buo7GFsy4k6RcP4VEfAmvafM4u/Wf3h1bbCP974NAXWfY2v3BaxiCbbrAKQ/lNYSFEOoeF0jdE+3OEfiWkA5WKaFhF8=,iv:teWxRj0Ws2fr0gEBPEmefM2+Df/0pI9F/sfI7iYOOrg=,tag:FLgnWcg76GGKrwUD4hAADg==,type:str]
    version: 3.13.1
