apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tuaanh03/ecommerce-infrastructure.git
    targetRevision: main
    path: apps/ecommerce

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: ecommerce-backend-deployment
    namespace: ecommerce
    jsonPointers:
      - /spec/replicas
